"""
File import/export operations for digitizer projects.
"""
import json
import csv
import datetime
import shutil
from pathlib import Path
from typing import Optional
from .models import ProjectData


class ImportExport:
    """Handles loading and saving project files."""
    
    @staticmethod
    def save_project(project: ProjectData, file_path: str) -> bool:
        """Save project to JSON file."""
        try:
            data = project.to_dict()
            # Add PDF path if it exists
            if project.pdf_path:
                data['pdf_path'] = project.pdf_path
            with open(file_path, 'w') as f:
                json.dump(data, f, indent=2)
            project.project_path = file_path
            project.modified = False
            return True
        except Exception as e:
            print(f"Failed to save project: {e}")
            return False
    
    @staticmethod
    def load_project(project: ProjectData, file_path: str) -> bool:
        """Load project from JSON file."""
        try:
            with open(file_path, 'r') as f:
                data = json.load(f)
            project.from_dict(data)
            # Load PDF path if it exists
            if 'pdf_path' in data:
                project.pdf_path = data['pdf_path']
            project.project_path = file_path
            project.modified = False
            return True
        except Exception as e:
            print(f"Failed to load project: {e}")
            return False
    
    @staticmethod
    def create_backup(file_path: str) -> Optional[str]:
        """Create a backup of the project file."""
        try:
            timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            backup_path = f"{file_path}.backup_{timestamp}"
            shutil.copy2(file_path, backup_path)
            return backup_path
        except Exception as e:
            print(f"Failed to create backup: {e}")
            return None
    
    @staticmethod
    def export_points_csv(project: ProjectData, file_path: str) -> bool:
        """Export points to CSV file."""
        try:
            with open(file_path, 'w', newline='') as f:
                writer = csv.writer(f)
                writer.writerow(['ID', 'Real_X', 'Real_Y', 'Z', 'PDF_X', 'PDF_Y', 'Hidden', 'Description'])
                for point in project.points:
                    writer.writerow([
                        point.id, point.real_x, point.real_y, point.z,
                        point.pdf_x, point.pdf_y, point.hidden, point.description
                    ])
            return True
        except Exception as e:
            print(f"Failed to export points: {e}")
            return False
    
    @staticmethod
    def export_lines_csv(project: ProjectData, file_path: str) -> bool:
        """Export lines to CSV file."""
        try:
            with open(file_path, 'w', newline='') as f:
                writer = csv.writer(f)
                writer.writerow(['ID', 'Start_ID', 'End_ID', 'Hidden', 'Description'])
                for line in project.lines:
                    writer.writerow([
                        line.id, line.start_id, line.end_id, line.hidden, line.description
                    ])
            return True
        except Exception as e:
            print(f"Failed to export lines: {e}")
            return False
    
    @staticmethod
    def export_curves_csv(project: ProjectData, file_path: str) -> bool:
        """Export curves to CSV file."""
        try:
            with open(file_path, 'w', newline='') as f:
                writer = csv.writer(f)
                writer.writerow(['ID', 'Start_ID', 'End_ID', 'Arc_Point_IDs', 'Hidden', 'Description'])
                for curve in project.curves:
                    arc_ids = ','.join(map(str, curve.arc_point_ids))
                    writer.writerow([
                        curve.id, curve.start_id, curve.end_id, arc_ids, curve.hidden, curve.description
                    ])
            return True
        except Exception as e:
            print(f"Failed to export curves: {e}")
            return False
    
    @staticmethod
    def export_grass_ascii(project: ProjectData, file_path: str) -> bool:
        """Export to GRASS ASCII vector format."""
        try:
            with open(file_path, 'w') as f:
                f.write("ORGANIZATION: 3D Maker Digitizer\n")
                f.write("DIGIT DATE:   " + datetime.datetime.now().strftime("%Y-%m-%d") + "\n")
                f.write("DIGIT NAME:   Digitizer\n")
                f.write("MAP NAME:     Track Definition\n")
                f.write("MAP DATE:     " + datetime.datetime.now().strftime("%Y") + "\n")
                f.write("MAP SCALE:    1\n")
                f.write("OTHER INFO:   Generated by 3D Maker Digitizer\n")
                f.write("ZONE:         0\n")
                f.write("MAP THRESH:   0.000000\n")
                f.write("VERTI:\n")
                
                # Export points
                for point in project.points:
                    if not point.hidden:
                        f.write(f"P  1 1\n {point.real_x} {point.real_y}\n 1     {point.id}\n")
                
                # Export lines
                for line in project.lines:
                    if not line.hidden:
                        start = project.get_point(line.start_id)
                        end = project.get_point(line.end_id)
                        if start and end:
                            f.write(f"L  2 1\n")
                            f.write(f" {start.real_x} {start.real_y}\n")
                            f.write(f" {end.real_x} {end.real_y}\n")
                            f.write(f" 1     {line.id}\n")
                
                # Export curves as polylines
                for curve in project.curves:
                    if not curve.hidden and curve.arc_points_real:
                        point_count = len(curve.arc_points_real)
                        f.write(f"L  {point_count} 1\n")
                        for px, py, pz in curve.arc_points_real:
                            f.write(f" {px} {py}\n")
                        f.write(f" 1     {curve.id}\n")
            
            return True
        except Exception as e:
            print(f"Failed to export GRASS ASCII: {e}")
            return False
    
    @staticmethod
    def export_sql(project: ProjectData, file_path: str) -> bool:
        """Export to SQL insert script for SeasPathDB."""
        try:
            with open(file_path, 'w') as f:
                f.write("-- SQL Insert Script for SeasPathDB\n")
                f.write("-- Generated from 3D Maker Digitizer\n\n")
                
                # Clear tables first (Curves, Lines, Points)
                f.write("-- Clear existing data (order: Curves, Lines, Points)\n")
                f.write("DELETE FROM SeasPathDB.dbo.Visualization_Curve;\n")
                f.write("DELETE FROM SeasPathDB.dbo.Visualization_Edge;\n")
                f.write("DELETE FROM SeasPathDB.dbo.Visualization_Coordinate;\n\n")
                
                # Points
                f.write("SET IDENTITY_INSERT SeasPathDB.dbo.Visualization_Coordinate ON;\n")
                for point in project.points:
                    if not point.hidden:
                        rx = int(round(point.real_x))
                        ry = int(round(point.real_y))
                        # Ensure Z is exported as an integer (0 stays 0)
                        z_val = int(round(point.z)) if point.z is not None else 0
                        desc = point.description.replace("'", "''") if point.description else ''
                        # Swap Y and Z axes on export: export Y<-Z and Z<-Y
                        f.write(f"INSERT INTO SeasPathDB.dbo.Visualization_Coordinate (Id, X, Y, Z, Description) VALUES ({point.id}, {rx}, {z_val}, {ry}, '{desc}');\n")
                f.write("SET IDENTITY_INSERT SeasPathDB.dbo.Visualization_Coordinate OFF;\n\n")
                
                # Lines
                f.write("SET IDENTITY_INSERT SeasPathDB.dbo.Visualization_Edge ON;\n")
                for line in project.lines:
                    if not line.hidden:
                        f.write(f"INSERT INTO SeasPathDB.dbo.Visualization_Edge (Id, TailCoordenate, HeadCoordenate) VALUES ({line.id}, {line.start_id}, {line.end_id});\n")
                f.write("SET IDENTITY_INSERT SeasPathDB.dbo.Visualization_Edge OFF;\n\n")
                
                # Curves (PositionNumber, CoordinateId, EdgeId) - no explicit Id
                for curve in project.curves:
                    if not curve.hidden and curve.arc_point_ids:
                        base_line = getattr(curve, 'base_line_id', 0)
                        arc_point_ids = curve.arc_point_ids
                        for pos, pid in enumerate(arc_point_ids):
                            pt = project.get_point(pid)
                            if pt and pt.z is not None:
                                z_comment = int(round(pt.z))
                            else:
                                z_comment = 'NA'
                            f.write(f"INSERT INTO SeasPathDB.dbo.Visualization_Curve (PositionNumber, CoordinateId, EdgeId) VALUES ({pos}, {pid}, {base_line}); -- Z:{z_comment}\n")
            
            return True
        except Exception as e:
            print(f"Failed to export SQL: {e}")
            return False
